name: CI
on:
  push:
    branches:
      - main
      - master
    tags:
      - '!*'  # Do not execute on tags
env:
  NAME:  ${{vars.NAME}}
  EMAIL: ${{vars.EMAIL}}
  NPM_TOKEN:    ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
  FORCE_COLOR: 1
  NODE_VERSION: lts/*
  DENO_VERSION: v2.x



jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macOS-latest]
    name: Test on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno test


  publish-jsr:
    name: Publish to JSR
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish

  publish-npm:
    name: Publish to NPM
    needs: [test, publish-jsr]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{env.DENO_VERSION}}
      - run: deno run -A jsr:@ryoppippi/mirror-jsr-to-npm
        env:
          PACKAGE_NAME: $(jq -r '.name' deno.json)
          PACKAGE_VERSION: $(jq -r '.version' deno.json)
          PACKAGE_DESCRIPTION: ${{github.event.repository.description}}
          PACKAGE_LICENSE: $(jq -r '.license' deno.json)
          PACKAGE_AUTHOR: 'wolfram77@gmail.com'
